# -*- coding: utf-8 -*-
"""person_based_predict_proba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tpj21zaZ9CEQtTq0jy-roXp-3DWUe7Tr
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.listdir('/content/drive/MyDrive/anemia_detection/datasets')

!unzip "/content/drive/MyDrive/anemia_detection/datasets/palpablepalm_dataset.zip"

!unrar x "/content/Anemia Detection using Palpable Palm Image Datasets from Ghana/Palm.rar"

!unzip "/content/drive/MyDrive/anemia_detection/datasets/conjunctiva_dataset.zip"

!unzip "/content/drive/MyDrive/anemia_detection/datasets/fingernails_dataset.zip"

!unrar x "/content/Detection of Anemia using Colour of the Fingernails Image Datasets from Ghana/Fingernails.rar"

import os
import re
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit

def extract_patient_key(path):
    filename = os.path.basename(path)
    name = os.path.splitext(filename)[0]

    # augmentation suffixlerini temizle: (2), (3), ..., (12)
    name = re.sub(r"\s*\(\d+\)$", "", name)

    # yazım hatasını düzelt
    name_lower = name.lower().replace("anrmic", "anemic")

    # sınıf bilgisi
    if name_lower.startswith("non"):
        label_text = "Non-Anemic"
        label = 0
    else:
        label_text = "Anemic"
        label = 1

    # dosya adındaki 3 haneli sayıyı al
    # örn: Anemic-001, Anemic-FN-001, Non-AnemicP-204
    nums = re.findall(r"(\d{3})", name_lower)

    if len(nums) == 0:
        return None, None, None

    patient_no = nums[-1]

    # RA, FV gibi varyantları kişi ID'ye dahil etmiyoruz
    patient_key = f"{label_text}_{patient_no}"

    return patient_key, label, label_text

import os
import glob
import pandas as pd

palm_paths = glob.glob(os.path.join("/content/Palm", "**", "*.png"), recursive=True)
nail_paths = glob.glob(os.path.join("/content/Fingernails", "**", "*.png"), recursive=True)
conj_paths = glob.glob(os.path.join(
    "/content/Application of Machine Learning in Detecting Iron Deficiency Anemia Using  Conjunctiva image Dataset from Ghana",
    "**",
    "*.png"
), recursive=True)


def build_dataframe(image_paths, modality):
    rows = []

    for path in image_paths:
        patient_key, label, label_text = extract_patient_key(path)

        if patient_key is None:
            continue

        rows.append({
            "path": path,
            "patient_key": patient_key,
            "label": label,
            "class": label_text,
            "modality": modality
        })

    return pd.DataFrame(rows)

df_palm = build_dataframe(palm_paths, "palm")
df_nail = build_dataframe(nail_paths, "nail")
df_conj = build_dataframe(conj_paths, "conjunctiva")

palm_ids = set(df_palm["patient_key"])
nail_ids = set(df_nail["patient_key"])
conj_ids = set(df_conj["patient_key"])

common_ids = palm_ids & nail_ids & conj_ids

print("Palm kişi sayısı:", len(palm_ids))
print("Nail kişi sayısı:", len(nail_ids))
print("Conjunctiva kişi sayısı:", len(conj_ids))
print("Üç veri setinde ortak kişi sayısı:", len(common_ids))

df_palm_common = df_palm[df_palm["patient_key"].isin(common_ids)].copy()
df_nail_common = df_nail[df_nail["patient_key"].isin(common_ids)].copy()
df_conj_common = df_conj[df_conj["patient_key"].isin(common_ids)].copy()

common_df = pd.DataFrame({
    "patient_key": sorted(list(common_ids))
})

common_df["label"] = common_df["patient_key"].apply(
    lambda x: 1 if x.startswith("Anemic") else 0
)

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(
        common_df,
        common_df["label"],
        groups=common_df["patient_key"]
    )
)

train_ids = set(common_df.iloc[train_idx]["patient_key"])
test_ids = set(common_df.iloc[test_idx]["patient_key"])

print("Train kişi sayısı:", len(train_ids))
print("Test kişi sayısı:", len(test_ids))
print("Train sınıf dağılımı:")
print(common_df.iloc[train_idx]["label"].value_counts())
print("Test sınıf dağılımı:")
print(common_df.iloc[test_idx]["label"].value_counts())

palm_train = df_palm_common[df_palm_common["patient_key"].isin(train_ids)]
palm_test  = df_palm_common[df_palm_common["patient_key"].isin(test_ids)]

nail_train = df_nail_common[df_nail_common["patient_key"].isin(train_ids)]
nail_test  = df_nail_common[df_nail_common["patient_key"].isin(test_ids)]

conj_train = df_conj_common[df_conj_common["patient_key"].isin(train_ids)]
conj_test  = df_conj_common[df_conj_common["patient_key"].isin(test_ids)]

# =========================
# FEATURE EXTRACTION FUNCTION
# =========================
import cv2
import numpy as np

def extract_features_from_df(df_exp):
    groups = []
    features = []
    labels = []

    for _, row in df_exp.iterrows():
        img = cv2.imread(row["path"])
        if img is None:
            continue

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        R = img[:, :, 0]
        G = img[:, :, 1]
        B = img[:, :, 2]

        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
        H, S, V = cv2.split(hsv)

        lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
        L, a, b = cv2.split(lab)

        R_mean = np.mean(R)
        G_mean = np.mean(G)
        B_mean = np.mean(B)

        features.append([
            np.mean(R), np.std(R),
            np.mean(G), np.std(G),
            np.mean(B), np.std(B),

            np.mean(L), np.std(L),
            np.mean(a), np.std(a),
            np.mean(b), np.std(b),

            np.mean(H), np.std(H),
            np.mean(S), np.std(S),
            np.mean(V), np.std(V),

            np.percentile(R, 25), np.percentile(R, 50), np.percentile(R, 75),
            np.percentile(G, 25), np.percentile(G, 50), np.percentile(G, 75),
            np.percentile(B, 25), np.percentile(B, 50), np.percentile(B, 75),

            R_mean / (G_mean + 1e-6),
            R_mean / (B_mean + 1e-6),
            G_mean / (B_mean + 1e-6),

            R_mean / (R_mean + G_mean + B_mean + 1e-6),
            G_mean / (R_mean + G_mean + B_mean + 1e-6),
            B_mean / (R_mean + G_mean + B_mean + 1e-6),

            np.mean(gray),
            np.std(gray),
            np.var(gray)
        ])

        labels.append(1 if row["class"] == "Anemic" else 0)
        groups.append(row["patient_key"])

    X = np.array(features, dtype=np.float32)
    y = np.array(labels, dtype=np.int32)
    groups = np.array(groups)

    return X, y, groups

X_palm_train, y_palm_train, groups_palm_train = extract_features_from_df(palm_train)
X_palm_test,  y_palm_test,  groups_palm_test  = extract_features_from_df(palm_test)

X_nail_train, y_nail_train, groups_nail_train = extract_features_from_df(nail_train)
X_nail_test,  y_nail_test,  groups_nail_test  = extract_features_from_df(nail_test)

X_conj_train, y_conj_train, groups_conj_train = extract_features_from_df(conj_train)
X_conj_test,  y_conj_test,  groups_conj_test  = extract_features_from_df(conj_test)

import numpy as np

def debug_dataset(name, X_train, y_train, X_test, y_test):
    print("\n====================")
    print(name)
    print("====================")

    # 1) Boş veri kontrolü
    print("Train size:", len(X_train))
    print("Test size:", len(X_test))

    # 2) Shape kontrolü
    if len(X_train) > 0:
        print("Train shape:", X_train.shape)
    if len(X_test) > 0:
        print("Test shape:", X_test.shape)

    # 3) NaN / inf kontrolü
    print("Train NaN:", np.isnan(X_train).sum())
    print("Train Inf:", np.isinf(X_train).sum())

    # 4) label dağılımı
    print("Train label dağılımı:", np.bincount(y_train) if len(y_train) > 0 else "EMPTY")
    print("Test label dağılımı:", np.bincount(y_test) if len(y_test) > 0 else "EMPTY")


# =========================
# ÇALIŞTIR
# =========================
debug_dataset("PALM", X_palm_train, y_palm_train, X_palm_test, y_palm_test)
debug_dataset("NAIL", X_nail_train, y_nail_train, X_nail_test, y_nail_test)
debug_dataset("CONJ", X_conj_train, y_conj_train, X_conj_test, y_conj_test)

from sklearn.ensemble import HistGradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.calibration import CalibratedClassifierCV

base_palm = HistGradientBoostingClassifier(
 max_iter=100,
 learning_rate=0.5,
 max_depth=None,
 min_samples_leaf=1,
 max_leaf_nodes=31,
 random_state=42
)
palm_model = CalibratedClassifierCV(
 estimator=base_palm,
 method="isotonic",
 cv=5
)
base_nail = HistGradientBoostingClassifier(
 max_iter=100,
 learning_rate=0.5,
 max_depth=None,
 min_samples_leaf=20,
 max_leaf_nodes=31,
 l2_regularization=0.0,
 random_state=42
)
nail_model = CalibratedClassifierCV(
 estimator=base_nail,
 method="isotonic",
 cv=5
)
base_conj = XGBClassifier(
 n_estimators=1000,
 max_depth=3,
 subsample=1,
 colsample_bytree=0.95,
 reg_lambda=10,
 eval_metric="logloss",
 random_state=42
)
conj_model = CalibratedClassifierCV(
 estimator=base_conj,
 method="sigmoid",
 cv=5
)

palm_model.fit(X_palm_train, y_palm_train)
nail_model.fit(X_nail_train, y_nail_train)
conj_model.fit(X_conj_train, y_conj_train)

#Test olasılıkları

palm_prob = palm_model.predict_proba(X_palm_test)[:, 1]
nail_prob = nail_model.predict_proba(X_nail_test)[:, 1]
conj_prob = conj_model.predict_proba(X_conj_test)[:, 1]

from sklearn.metrics import brier_score_loss, log_loss, roc_auc_score, f1_score
from sklearn.metrics import brier_score_loss

palm_pred = (palm_prob >= 0.5).astype(int)

print("PALM METRICS")
print("Brier:", brier_score_loss(y_palm_test, palm_prob))
print("LogLoss:", log_loss(y_palm_test, palm_prob))
print("AUC:", roc_auc_score(y_palm_test, palm_prob))
print("F1:", f1_score(y_palm_test, palm_pred))

nail_pred = (nail_prob >= 0.5).astype(int)

print("NAIL METRICS")
print("Brier:", brier_score_loss(y_nail_test, nail_prob))
print("LogLoss:", log_loss(y_nail_test, nail_prob))
print("AUC:", roc_auc_score(y_nail_test, nail_prob))
print("F1:", f1_score(y_nail_test, nail_pred))

conj_pred = (conj_prob >= 0.5).astype(int)

print("CONJ METRICS")
print("Brier:", brier_score_loss(y_conj_test, conj_prob))
print("LogLoss:", log_loss(y_conj_test, conj_prob))
print("AUC:", roc_auc_score(y_conj_test, conj_prob))
print("F1:", f1_score(y_conj_test, conj_pred))

from sklearn.calibration import calibration_curve
import matplotlib.pyplot as plt

prob_true, prob_pred = calibration_curve(y_palm_test, palm_prob, n_bins=10)

plt.figure()
plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0, 1], [0, 1])
plt.title("El Ayası Kalibrasyon Eğrisi")
plt.xlabel("Tahmin Edilen Olasılık")
plt.ylabel("Gerçek Olasılık")
plt.show()


prob_true, prob_pred = calibration_curve(y_nail_test, nail_prob, n_bins=10)

plt.figure()
plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0, 1], [0, 1])
plt.title("Tırnak Kalibrasyon Eğrisi")
plt.xlabel("Tahmin Edilen Olasılık")
plt.ylabel("Gerçek Olasılık")
plt.show()


prob_true, prob_pred = calibration_curve(y_conj_test, conj_prob, n_bins=10)

plt.figure()
plt.plot(prob_pred, prob_true, marker='o')
plt.plot([0, 1], [0, 1])
plt.title("Konjonktiva Kalibrasyon Eğrisi")
plt.xlabel("Tahmin Edilen Olasılık")
plt.ylabel("Gerçek Olasılık")
plt.show()

def make_prob_df(test_df, probs, name):
    temp = test_df.copy()
    temp[name] = probs

    patient_prob = temp.groupby("patient_key").agg(
        y_true=("label", "first"),
        prob=(name, "mean")
    ).reset_index()

    patient_prob = patient_prob.rename(columns={"prob": name})

    return patient_prob

palm_prob_df = make_prob_df(palm_test, palm_prob, "palm_prob")
nail_prob_df = make_prob_df(nail_test, nail_prob, "nail_prob")
conj_prob_df = make_prob_df(conj_test, conj_prob, "conj_prob")

fusion_df = palm_prob_df.merge(
    nail_prob_df[["patient_key", "nail_prob"]],
    on="patient_key"
).merge(
    conj_prob_df[["patient_key", "conj_prob"]],
    on="patient_key"
)

print(fusion_df.head())
print("Füzyon test kişi sayısı:", len(fusion_df))

import joblib
import os

save_path = "/content/drive/MyDrive/anemia_detection/saved_models/01062026"
os.makedirs(save_path, exist_ok=True)

joblib.dump(palm_model, os.path.join(save_path, "palm_model.pkl"))
joblib.dump(nail_model, os.path.join(save_path, "nail_model.pkl"))
joblib.dump(conj_model, os.path.join(save_path, "conj_model.pkl"))

fusion_df["final_prob"] = (
    0.45 * fusion_df["palm_prob"] +
    0.35 * fusion_df["nail_prob"] +
    0.20 * fusion_df["conj_prob"]
)

fusion_df["final_pred"] = (fusion_df["final_prob"] >= 0.5).astype(int)

from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.metrics import precision_score, recall_score, confusion_matrix

y_true = fusion_df["y_true"]
y_pred = fusion_df["final_pred"]
y_prob = fusion_df["final_prob"]

print("Fusion Accuracy:", accuracy_score(y_true, y_pred))
print("Fusion F1-score:", f1_score(y_true, y_pred))
print("Fusion AUC:", roc_auc_score(y_true, y_prob))
print("Fusion Precision:", precision_score(y_true, y_pred))
print("Fusion Recall:", recall_score(y_true, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Tahmin Edilen Sınıf")
plt.ylabel("Gerçek Sınıf")
plt.title("Füzyon Karmaşıklık Matrisi")
plt.show()







!pip install skl2onnx onnx onnxmltools

!pip install skl2onnx onnxmltools onnx

import os
import numpy as np
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
from onnxmltools import convert_xgboost

save_path = "/content/drive/MyDrive/anemia_detection/saved_models/onnx"
os.makedirs(save_path, exist_ok=True)

# =========================
# PALM
# =========================
initial_type = [("input", FloatTensorType([None, X_palm_train.shape[1]]))]

palm_onnx = convert_sklearn(
    palm_model.estimator,
    initial_types=initial_type,
    target_opset=12
)

with open(os.path.join(save_path, "palm_model.onnx"), "wb") as f:
    f.write(palm_onnx.SerializeToString())

# =========================
# NAIL
# =========================
initial_type = [("input", FloatTensorType([None, X_nail_train.shape[1]]))]

nail_onnx = convert_sklearn(
    nail_model.estimator,
    initial_types=initial_type,
    target_opset=12
)

with open(os.path.join(save_path, "nail_model.onnx"), "wb") as f:
    f.write(nail_onnx.SerializeToString())

# =========================
# CONJ (XGBoost)
# =========================
initial_type = [("input", FloatTensorType([None, X_conj_train.shape[1]]))]

conj_onnx = convert_xgboost(
    conj_model.estimator,
    initial_types=initial_type
)

with open(os.path.join(save_path, "conj_model.onnx"), "wb") as f:
    f.write(conj_onnx.SerializeToString())

print("ONNX export tamamlandı")

